### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by imSrbh** [spmallick/learnopencv#328]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-5f0d120045e2> in <module>()
      9 #     plt.figure()
     10 #     plt.imshow(255*np.uint8(probMap>threshold))
---> 11     keypoints = getKeypoints(probMap, threshold)
     12     print("Keypoints - {} : {}".format(keypointsMapping[part], keypoints))
     13     keypoints_with_id = []

<ipython-input-3-8d53aac137bd> in getKeypoints(probMap, threshold)
      8 
      9     #find the blobs
---> 10     _, contours, _ = cv2.findContours(mapMask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
     11 
     12     #for each blob find the maxima

ValueError: not enough values to unpack (expected 3, got 2)

**Comment by srikar8** [comment]
Hi @imSrbh , It is because of Opencv version.

change line 
 _, contours, _ = cv2.findContours(mapMask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE
to
 **contours, _ = cv2.findContours(mapMask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE**


opencv 3.4 - https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html
opencv 4.1 - https://docs.opencv.org/master/d4/d73/tutorial_py_contours_begin.html

**Comment by imSrbh** [comment]
Hello @srikar8 , thanks alot for Helping.
It works for me.
