### ISSUE TITLE
error cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\ptsetreg.cpp:1108: error: (-215:Assertion failed) count >= 0 && to.checkVector(2) == count in function 'cv::estimateAffinePartial2D'

### ISSUE THREAD

**Issue by gopig99** [spmallick/learnopencv#720]
Hi,
I have annotated a glasses and while running got this error
""""""
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\calib3d\src\ptsetreg.cpp:1108: error: (-215:Assertion failed) count >= 0 && to.checkVector(2) == count in function 'cv::estimateAffinePartial2D'

[ WARN:1@19.242] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
""""""
Can anyone help me in solving this
Thanks in advance

**Comment by LilLouis5** [comment]
Hi,gopig.

Because of your method does not fit the paraments, so it can not use that method 'cv::estimateAffinePartial2D'

Here are two method to solve the problem.

Firstly, you can use cv2.estimateAffinePartial2D() to instead the old method.
Secondly, you can degrade your OpenCV version.

In my view, i actually adverse your to solve the problem with method1. 

I wish it can help u.

Lil louis -2023.3.22 China

**Comment by YoungWaai** [comment]
Hi LolLouis

Could you demonstrate how to use  cv2.estimateAffinePartial2D()  to replace the old method?

Thanks!
