### ISSUE TITLE
YOLOv7-Object-Detection-Paper-Explanation-and-Inference - for custom Yolov7 model.

### ISSUE THREAD

**Issue by magicsoft75** [spmallick/learnopencv#752]
Hi.
Can you help me: I need a simple sample detection code to run with my own model - less complicated than in detect.py from the Yolov7 repository :-)
Thank you

**Comment by brmarkus** [comment]
What have you tried so far?
Which "Yolov7 repository" do you mean?
What is "simple enough" ;-) ?

Have you tried removing unneeded parts (like removing additional imported modules, remove support for all-files-in-a-directory and just keep the support for e.g. a single image or a single video, remove measurements&statistics, etc.).

I converted some of the YoloV7 models to e.g. ONNX (using e.g. "python3 export.py ... ... ..") - and then used various OpenVINO samples from the Open-Model-Zoo.

**Comment by magicsoft75** [comment]
Thank you. I have started changing the original file.

**Comment by brmarkus** [comment]
Have you heard, have you tried, are you familiar with OpenVINO and its open-model-zoo? There you can find plenty of more or less complex samples for e.g. object-detection scenarios (which might get minor adaptions for the YoloV7 input's and output's requirements).

@magicsoft75 Anything left otherwise? Feel free to close this issue.

**Comment by magicsoft75** [comment]
I heard but I did not apply. I tried it and I like it. Thank you. I close.
